TCP_PORT = 42000
SERVER_HOST_IP = "10.0.0.2"
SERVER_HOST_PORT = 42000
MAX_CONNECTIONS = 10
PCAP_FILE_NAME = 'merged10.147.80.139.pcap'
REQUEST_NATURE_SCRIPT = 'test_packets.py'
SERVER_SCRIPT_PATH = '~/physical2/working_model/server_starter.py'
MODEL_PATH = '~/physical2/working_model'
CLIENT_SUBNET='10.147.80'

# PACKET METRIC CONSTANTS
PAYLOAD_INTERVAL_SIZE = 100  # 100 BYTE INTERVALS
PAYLOAD_INTERVAL_NUM  = 1000 # NUMBER OF INTERVALS
DELAY_INTERVAL_SIZE   = 0.005 # SECONDS
DELAY_INTERVAL_NUM   = 10000
FLOAT_PRECISION = 5 # DEFAULT DECIMAL PLACES TO BE CONSIDERED
