# AUTH TOKEN DEETS
AUTH_TOKEN_URL='127.0.0.1:PORT'
AUTH_TOKEN_JSON_FNAME='./jsonfiles/auth_token_json.json'
AUTH_TOKEN_KEY='X-Subject-Token'

#ACCESS_TOKEN_URL='127.0.0.1:PORT'
#ACCESS_TOKEN_JSON_FNAME='./jsonfiles/access_token_json.json'
#ACCESS_TOKEN_KEY='ACCESS-KEY'
