TCP_PORT = 42000
SERVER_HOST_IP = "10.0.0.2"
SERVER_HOST_PORT = 42000
MAX_CONNECTIONS = 10
PCAP_FILE_NAME = 'merged10.147.80.139.pcap'
REQUEST_NATURE_SCRIPT = 'test_packets.py'
SERVER_SCRIPT_PATH = '~/physical2/working_model/server_starter.py'
MODEL_PATH = '~/physical2/working_model'
CONTROLLER_ETH="a8:60:b6:10:c6:4d"
NFV_MACHINE_MAC="ac:1f:6b:66:c2:be"
INTERNET_SWITCH_PORT = 5
CONTROLLER_SWITCH_PORT = 1
# SCALING
METRIC_THRESHOLD = 10 # IF CPU UTIL ABOVE THIS VALUE THEN SCALE UP
